spring.application.name=449-final-project
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=cpsc449final

jwt.secret= dXe/D9CDOcXl6E16hxDoYTkrQ5uHb6c+BXOdB0suHxdflTjqWXqnTh4z64S61jSl
tk+VQ+HFWI79WP7qspCcIw==
# expires in 1 day
jwt.expiration =  86400000 